### ISSUE TITLE
In US state list there is 2 entry " New Jersey and New Jersy " ,I think New Jersy is just spelling mistake

### ISSUE THREAD

**Issue by ashjha1** [harpreetkhalsagtbit/country-state-city#1]

**Comment by nitinsh99** [comment]
Getting the same issue. Can the author please fix it?

**Comment by DillonStreator** [comment]
Unfortunately, I don't believe that this is the only issue here.
There are 60 states appearing for the US..
New Mexico, Byram, Cokato?

I do wonder if this repo is still active at all.

**Comment by harpreetkhalsagtbit** [comment]
1194ebf71d362e984fccea35d6644fbe71039400
