### ISSUE TITLE
switching to typescript and/or type definition?

### ISSUE THREAD

**Issue by baywet** [harpreetkhalsagtbit/country-state-city#10]
Hey!
Thanks for putting together this project.
Would you consider switching to typescript or at least adding type definitions?
This way we'd have compile time validation.

**Comment by harpreetkhalsagtbit** [comment]
@baywet 
Yes definitely, let me know how to proceed?

**Comment by baywet** [comment]
At a high level:
1. rename index.js to index.ts
1. you might have code modifications suggestions from your IDE to improve maintainability and more, apply those (might be optional depending on the code)
1. `npm i typescript -D`
1. add a `"types": "index.ts"` entry in your package.json
1. add a `"build": "tsc -p tsconfig.json"` in the `scripts` section of your package.json
1. add a `tsconfig.json` a the root of your project, now the bulk of the effort is going to define the proper configuration that suits your project. Here is some documentation [about the file ](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html).

And that should be about it. If you want to work on a feature branch so this way we'll be able to compare and I'll be able to provide guidance to you.

**Comment by harpreetkhalsagtbit** [comment]
@baywet 
please check this branch
https://github.com/harpreetkhalsagtbit/country-state-city/tree/switch-to-typescript

I tested locally installing this package but it installs lib and node_modules also. It should not include these files to publish. Can you please guide me on this. I have used .npmingore.

**Comment by harpreetkhalsagtbit** [comment]
check this P.R #12

**Comment by baywet** [comment]
fixed by #12
