### ISSUE TITLE
V3.0.5 is giving error -> "Can't resolve fs"

### ISSUE THREAD

**Issue by jessica1401** [harpreetkhalsagtbit/country-state-city#108]
After updating my version to 3.0.5, It's giving me an error that "Can't resolve fs".
The case of this error is in node_module/country-state-city

**Comment by jonathan-mcewan** [comment]
looks like this PR broke it 13hours ago: https://github.com/harpreetkhalsagtbit/country-state-city/pull/106

**Comment by jonathan-mcewan** [comment]
@jessica1401 I just rollback to 3.0.4 :man-shrugging:

**Comment by harpreetkhalsagtbit** [comment]
@jonathan-mcewan @jessica1401 I will revert this release soon.

**Comment by harpreetkhalsagtbit** [comment]
> @jonathan-mcewan @jessica1401 I will revert this release soon.

reverted
