### ISSUE TITLE
Does this work with react native ?

### ISSUE THREAD

**Issue by karanpratapsingh** [harpreetkhalsagtbit/country-state-city#16]
Does this work with react native?

**Comment by harpreetkhalsagtbit** [comment]
haven't tried yet. You please give it a try and let us know.

**Comment by karanpratapsingh** [comment]
@harpreetkhalsagtbit I tried it doesn't work, Error: maximum call stack reached

**Comment by wkoutre** [comment]
@karanpratapsingh You can use my fork: https://github.com/wkoutre/country-state-city.git

I ran into `Error: maximum call stack reached`, and so I stripped out the loading of `cityList`, and updated the README in my fork, accordingly, removing the inclusion of the affected methods:

- getCityById
- getCitiesOfState

For my project, this is all I need. Hope it helps!
