### ISSUE TITLE
Need to request states by country code

### ISSUE THREAD

**Issue by karljv** [harpreetkhalsagtbit/country-state-city#17]
giving only a getStatesOfCountry( _id: number ) function to fetch the list of states per country, where _id is a proprietary numeric ID of that country, is a bad idea.

Most databases have their own country id-s already built into them and there should be an option to getStatesOfCountryByCountryCode( _code: string ) option. 

Where for example _code === "US", which is standardised and environment independent.

This is both an issue and a friendly suggestion from me, because this issue keeps me from using this library in larger projects, because there is already an established countryId system in place and those ID-s do not correlate with the ones in this repo.

**Comment by harpreetkhalsagtbit** [comment]
@karljv, Sure.
Will definitely release an API for that in next release.
