### ISSUE TITLE
getCountryById, getStateById, getCityById all returns incorrect information

### ISSUE THREAD

**Issue by mikylebaksh** [harpreetkhalsagtbit/country-state-city#2]
getCountryById(), getStateById(), and getCityById() returns incorrect information. It will always return the record 1 ahead of the intended.

This is because these methods are access the country, state, and city arrays by index instead finding by id.

Reproduce: 

```javascript
import Csc from 'country-state-city'

var afghanistanCountry = Csc.getAllCountries()[0];

// afghanistanCountry === {
//   "id": "1",
//   "sortname": "AF",
//   "name": "Afghanistan",
//   "phonecode": "93"
// }

var albaniaCountry = Csc.getCountryById(1);

// albaniaCountry === {
//   "id": "2",
//   "sortname": "AL",
//   "name": "Albania",
//   "phonecode": "355"
// }
```

**Comment by roksollc** [comment]
I encountered the same problem, corrected it, and submitted a pull request.
