### ISSUE TITLE
It fails to install after latest update

### ISSUE THREAD

**Issue by amrita-syn** [harpreetkhalsagtbit/country-state-city#28]
Node: 11.10.1

` > 6 | import csc from 'country-state-city';`
`               | ^`
`You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].
    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string`

Had to specify version for the CI to pass. 
`"country-state-city": "1.0.2"`

**Comment by harpreetkhalsagtbit** [comment]
Its fixed now, please check.
Thanks
