### ISSUE TITLE
Can not find a city (Caracas capital of Venezuela) and the name of the state is wrong

### ISSUE THREAD

**Issue by gutoccs** [harpreetkhalsagtbit/country-state-city#3]
Hi!

The name of the state is wrong. Indicates **Distrito Federal** (id: 4029) when it is **Distrito Capital**. It is a state of Venezuela (id: 237). https://en.wikipedia.org/wiki/Capital_District_(Venezuela). Observation: It is **Distrito Capital** in Spanish.

**Caracas** does not appear. **Caracas** belongs to the **Distrito Capital** (id: 4029) and is the **capital of Venezuela** (id: 237).

This I reported in the repository: https://github.com/hiiamrohit/Countries-States-Cities-database **as issue**: https://github.com/hiiamrohit/Countries-States-Cities-database/issues/80

Thank you.

P.S. Excuse my English.

**Comment by harpreetkhalsagtbit** [comment]
Added  `Distrito` Federal as `Distrito Federal/Capital District` both name supported for now
