### ISSUE TITLE
record of Auckland is repeated twice in states.json.

### ISSUE THREAD

**Issue by vishnuroshan** [harpreetkhalsagtbit/country-state-city#30]
Auckland is present twice in `states.json.` as id: 245 and 2604 with different `country_id`

`{
		"id": "2604",
		"name": "Auckland",
		"country_id": "157"
	}`

and

`	{
		"id": "245",
		"name": "Auckland",
		"country_id": "13"
	}`

cities in auckland are also split between them

**Comment by harpreetkhalsagtbit** [comment]
fixed
