### ISSUE TITLE
Can we use dr5hn/countries-states-cities-database ?

### ISSUE THREAD

**Issue by dr5hn** [harpreetkhalsagtbit/country-state-city#43]
@harpreetkhalsagtbit Just a suggestion,

Can we use this DB?
https://github.com/dr5hn/countries-states-cities-database

Pros:
---
- It is more robust compare to your current one.
- It is updated more frequently and hence it remains error-free.
- By using this DB, the most maximum of your issues of data erroneous will close automagically. 😄 

P.S. If you want I can help you with whatever JSON format you require to make your efforts a little less. 🥂

**Comment by harpreetkhalsagtbit** [comment]
@dr5hn 
Please go ahead!

**Comment by dr5hn** [comment]
@harpreetkhalsagtbit 

I did the export according to a format that is required by this library. But I am worried about the `id` field. It doesn't match with your current one.

Do people use the `id` column?

You can check the exports here. https://github.com/harpreetkhalsagtbit/country-state-city/compare/master...dr5hn:update/Data?expand=1

**Comment by dr5hn** [comment]
@harpreetkhalsagtbit Waiting for your inputs..

**Comment by harpreetkhalsagtbit** [comment]
I want to get rid of these Ids and use country state city codes. But not all cities/states have unique codes

**Comment by harpreetkhalsagtbit** [comment]
.

**Comment by dr5hn** [comment]
@harpreetkhalsagtbit 

You're right !! ID is playing important role in the database. If we migrate to this [database](https://github.com/dr5hn/countries-states-cities-database), It will become backward incompatible.

**Comment by harpreetkhalsagtbit** [comment]
@dr5hn 
Backward compatibility won't be any big issue. If the database is accurate and gets update regularly we can move ahead.

**Comment by dr5hn** [comment]
@harpreetkhalsagtbit 

Ok then Raise a PR. https://github.com/harpreetkhalsagtbit/country-state-city/pull/44
