### ISSUE TITLE
Return Undefined?

### ISSUE THREAD

**Issue by kishanio** [harpreetkhalsagtbit/country-state-city#66]
Is there a reason why we return empty string and not undefined, 

https://github.com/harpreetkhalsagtbit/country-state-city/blob/a6ed49591b9c836948fde4fb4c3219d93187b5a5/lib/country.ts#L7

**Comment by harpreetkhalsagtbit** [comment]
@kishanio thanks for pointing this out. I was confused here - should have go with the `undefined` in the first place.

**Comment by kishanio** [comment]
@harpreetkhalsagtbit yes. Do you want me to take a look at this?

**Comment by harpreetkhalsagtbit** [comment]
Thanks.....But I have made the changes... will add more tests and release this weekend.

**Comment by harpreetkhalsagtbit** [comment]
fixed and released
