### ISSUE TITLE
Nigeria | Missing States

### ISSUE THREAD

**Issue by gettoknowdavid** [harpreetkhalsagtbit/country-state-city#67]
Some states in Nigeria are missing - the FCT (Abuja) and Rivers State.

`[
0: {name: "Abia State", isoCode: "AB", countryCode: "NG", latitude: "5.45273540", longitude: "7.52484140"}
1: {name: "Adamawa State", isoCode: "AD", countryCode: "NG", latitude: "9.32647510", longitude: "12.39838530"}
2: {name: "Akwa Ibom State", isoCode: "AK", countryCode: "NG", latitude: "4.90573710", longitude: "7.85366750"}
3: {name: "Anambra State", isoCode: "AN", countryCode: "NG", latitude: "6.22089970", longitude: "6.93695590"}
4: {name: "Bauchi State", isoCode: "BA", countryCode: "NG", latitude: "10.77606240", longitude: "9.99919430"}
5: {name: "Bayelsa State", isoCode: "BY", countryCode: "NG", latitude: "4.77190710", longitude: "6.06985260"}
6: {name: "Benue State", isoCode: "BE", countryCode: "NG", latitude: "7.33690240", longitude: "8.74036870"}
7: {name: "Borno State", isoCode: "BO", countryCode: "NG", latitude: "11.88463560", longitude: "13.15196650"}
8: {name: "Cross River State", isoCode: "CR", countryCode: "NG", latitude: "5.87017240", longitude: "8.59880140"}
9: {name: "Delta State", isoCode: "DE", countryCode: "NG", latitude: "33.74537840", longitude: "-90.73545080"}
10: {name: "Ebonyi State", isoCode: "EB", countryCode: "NG", latitude: "6.26492320", longitude: "8.01373020"}
11: {name: "Edo State", isoCode: "ED", countryCode: "NG", latitude: "6.63418310", longitude: "5.93040560"}
12: {name: "Ekiti State", isoCode: "EK", countryCode: "NG", latitude: "7.71898620", longitude: "5.31095050"}
13: {name: "Enugu State", isoCode: "EN", countryCode: "NG", latitude: "6.53635300", longitude: "7.43561940"}
14: {name: "Federal Capital Territory", isoCode: "FC", countryCode: "NG", latitude: "8.89406910", longitude: "7.18604020"}
15: {name: "Gombe State", isoCode: "GO", countryCode: "NG", latitude: "10.36377950", longitude: "11.19275870"}
16: {name: "Imo State", isoCode: "IM", countryCode: "NG", latitude: "5.57201220", longitude: "7.05882190"}
17: {name: "Jigawa State", isoCode: "JI", countryCode: "NG", latitude: "12.22801200", longitude: "9.56158670"}
18: {name: "Kaduna State", isoCode: "KD", countryCode: "NG", latitude: "10.37640060", longitude: "7.70945370"}
19: {name: "Kano State", isoCode: "KN", countryCode: "NG", latitude: "11.74706980", longitude: "8.52471070"}
20: {name: "Katsina State", isoCode: "KT", countryCode: "NG", latitude: "12.37967070", longitude: "7.63057480"}
21: {name: "Kebbi State", isoCode: "KE", countryCode: "NG", latitude: "11.49420030", longitude: "4.23333550"}
22: {name: "Kogi State", isoCode: "KO", countryCode: "NG", latitude: "7.73373250", longitude: "6.69058360"}
23: {name: "Kwara State", isoCode: "KW", countryCode: "NG", latitude: "8.96689610", longitude: "4.38740510"}
24: {name: "Lagos", isoCode: "LA", countryCode: "NG", latitude: "6.52437930", longitude: "3.37920570"}
25: {name: "Nasarawa State", isoCode: "NA", countryCode: "NG", latitude: "8.49979080", longitude: "8.19969370"}
26: {name: "Niger State", isoCode: "NI", countryCode: "NG", latitude: "9.93092240", longitude: "5.59832100"}
27: {name: "Ogun State", isoCode: "OG", countryCode: "NG", latitude: "6.99797470", longitude: "3.47373780"}
28: {name: "Ondo State", isoCode: "ON", countryCode: "NG", latitude: "6.91486820", longitude: "5.14781440"}
29: {name: "Osun State", isoCode: "OS", countryCode: "NG", latitude: "7.56289640", longitude: "4.51995930"}
30: {name: "Oyo State", isoCode: "OY", countryCode: "NG", latitude: "8.15738090", longitude: "3.61465340"}
31: {name: "Plateau State", isoCode: "PL", countryCode: "NG", latitude: "9.21820930", longitude: "9.51794880"}
32: {name: "Sokoto State", isoCode: "SO", countryCode: "NG", latitude: "13.05331430", longitude: "5.32227220"}
33: {name: "Taraba State", isoCode: "TA", countryCode: "NG", latitude: "7.99936160", longitude: "10.77398630"}
34: {name: "Yobe State", isoCode: "YO", countryCode: "NG", latitude: "12.29387600", longitude: "11.43904110"}
35: {name: "Zamfara State", isoCode: "ZA", countryCode: "NG", latitude: "12.12218050", longitude: "6.22358190"}
]`

I hope you can fix this soon enough.

Thank you.

**Comment by harpreetkhalsagtbit** [comment]
@dr5hn can you please look into this?

**Comment by dr5hn** [comment]
@harpreetkhalsagtbit Sure i can take this up.

**Comment by harpreetkhalsagtbit** [comment]
thanks @dr5hn

**Comment by dr5hn** [comment]
@gettoknowdavid Fixed in #68

@harpreetkhalsagtbit Please review.

**Comment by gettoknowdavid** [comment]
Thanks a lot. Working well.
